totem {
    version: 2
    cluster_name: dbcluster
    transport: knet
    token: 5000
}

nodelist {
    node {
        ring0_addr: 10.0.1.11
        name: node1
        nodeid: 1
    }
    node {
        ring0_addr: 10.0.1.12
        name: node2
        nodeid: 2
    }
}

quorum {
    provider: corosync_votequorum
    two_node: 1
}
