totem {
    version: 2
    cluster_name: dbcluster
    transport: knet
    crypto_cipher: aes256
    crypto_hash: sha256
    token: 5000
    token_retransmits_before_loss_const: 10
}

nodelist {
    node {
        ring0_addr: 10.0.1.11
        name: node1
        nodeid: 1
    }
    node {
        ring0_addr: 10.0.1.12
        name: node2
        nodeid: 2
    }
}

quorum {
    provider: corosync_votequorum
    two_node: 1
}

logging {
    to_logfile: yes
    logfile: /var/log/cluster/corosync.log
    to_syslog: yes
}
